// provus-frontend-platform/app/components/Monitoramento/ActivityFeed/index.vue
<script setup lang="ts">
import type { ILogAtividade } from "~/types/IMonitoring";
import TipoAtividadeEnum from "~/enums/TipoAtividadeEnum";

defineProps<{
  atividades: ILogAtividade[];
}>();

const activityVisualsMap = {
  [TipoAtividadeEnum.ENTROU]: { icon: "i-lucide-log-in", color: "blue" },
  [TipoAtividadeEnum.FINALIZOU]: {
    icon: "i-lucide-check-circle",
    color: "green",
  },
  [TipoAtividadeEnum.PAUSOU]: {
    icon: "i-lucide-pause-circle",
    color: "yellow",
  },
  [TipoAtividadeEnum.RETOMOU]: {
    icon: "i-lucide-play-circle",
    color: "yellow",
  },
  [TipoAtividadeEnum.PENALIDADE]: {
    icon: "i-lucide-shield-alert",
    color: "red",
  },
};

function formatTimestamp(timestamp: string): string {
  return new Date(timestamp).toLocaleTimeString("pt-BR", {
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
  });
}
</script>

<template>
  <UCard>
    <template #header>
      <h2 class="text-xl font-semibold text-gray-900">
        Atividade em Tempo Real
      </h2>
    </template>
    <div class="space-y-3 max-h-[450px] overflow-y-auto">
      <div
        v-for="activity in atividades"
        :key="activity.id"
        class="flex items-center space-x-3 p-3 bg-white rounded-lg border border-gray-200 hover:bg-gray-50 transition-colors"
      >
        <div
          :class="`bg-${activityVisualsMap[activity.tipo].color}-100`"
          class="w-8 h-8 rounded-full flex items-center justify-center shrink-0"
        >
          <Icon
            :name="activityVisualsMap[activity.tipo].icon"
            :class="`text-${activityVisualsMap[activity.tipo].color}-600`"
            class="text-sm"
          />
        </div>
        <div class="flex-1">
          <p class="text-sm font-medium text-gray-900">
            <span class="font-bold">{{ activity.alunoNome }}</span>
            {{ activity.descricao }}
          </p>
          <p class="text-xs text-gray-500">
            {{ formatTimestamp(activity.timestamp) }}
          </p>
        </div>
      </div>
    </div>
  </UCard>
</template>

// provus-mobile-platform/components/ActivityFeed.tsx
import React from "react";
import { View, Text, FlatList } from "react-native";
import {
  LogIn,
  CheckCircle,
  PauseCircle,
  PlayCircle,
  AlertTriangle,
} from "lucide-react-native";
import { ILogAtividade } from "../types/IMonitoring";
import { TipoAtividadeEnum } from "../enums/TipoAtividadeEnum";

interface Props {
  atividades: ILogAtividade[];
}

export default function ActivityFeed({ atividades }: Props) {
  const getIcon = (tipo: TipoAtividadeEnum) => {
    switch (tipo) {
      case TipoAtividadeEnum.ENTROU:
        return { icon: LogIn, color: "#3b82f6", bg: "bg-blue-100" };
      case TipoAtividadeEnum.FINALIZOU:
        return { icon: CheckCircle, color: "#22c55e", bg: "bg-green-100" };
      case TipoAtividadeEnum.PAUSOU:
        return { icon: PauseCircle, color: "#eab308", bg: "bg-yellow-100" };
      case TipoAtividadeEnum.RETOMOU:
        return { icon: PlayCircle, color: "#eab308", bg: "bg-yellow-100" };
      case TipoAtividadeEnum.PENALIDADE:
        return { icon: AlertTriangle, color: "#ef4444", bg: "bg-red-100" };
      default:
        return { icon: LogIn, color: "#6b7280", bg: "bg-gray-100" };
    }
  };

  const renderItem = ({ item }: { item: ILogAtividade }) => {
    const visual = getIcon(item.tipo);
    const IconComponent = visual.icon;

    let time = "00:00";
    try {
      time = new Date(item.timestamp).toLocaleTimeString("pt-BR", {
        hour: "2-digit",
        minute: "2-digit",
      });
    } catch {
      time = "--:--";
    }

    return (
      <View className="flex-row items-center mb-3">
        <View
          className={`w-8 h-8 rounded-full items-center justify-center mr-3 ${visual.bg}`}
        >
          <IconComponent size={14} color={visual.color} />
        </View>
        <View className="flex-1 border-b border-gray-100 pb-3">
          <Text className="text-xs text-gray-400 mb-0.5">{time}</Text>
          <Text className="text-sm text-gray-800">
            <Text className="font-bold">{item.alunoNome}</Text> {item.descricao}
          </Text>
        </View>
      </View>
    );
  };

  return (
    <View className="bg-white p-4 rounded-xl border border-gray-200 flex-1">
      <Text className="text-lg font-bold text-gray-900 mb-4">
        Atividade Recente
      </Text>

      <FlatList
        data={atividades}
        keyExtractor={(item) => String(item.id)}
        renderItem={renderItem}
        showsVerticalScrollIndicator={false}
        scrollEnabled={false} 
        ListEmptyComponent={
          <Text className="text-gray-400 text-center py-4">
            Nenhuma atividade registrada.
          </Text>
        }
      />
    </View>
  );
}
