// provus-mobile-platform/components/AnsweredQuestionCard.tsx
import React, { useState } from "react";
import {
  View,
  Text,
  TextInput,
  TouchableOpacity,
  ActivityIndicator,
} from "react-native";
import HtmlWithMath from "./ui/HtmlWithMath";
import {
  CheckCircle2,
  XCircle,
  Circle,
  MessageSquare,
  Save,
} from "lucide-react-native";
import {
  AvaliadorQuestaoDetalheApiResponse,
  EstadoQuestaoCorrigida,
} from "../types/api/response/AvaliadorQuestaoDetalhe.response";
import { TipoQuestaoEnum } from "../enums/TipoQuestaoEnum";
import { useCorrectionStore } from "../stores/correctionStore";
import { useToast } from "../hooks/useToast";

interface Props {
  questao: AvaliadorQuestaoDetalheApiResponse;
  numero: number;
  applicationId: number;
  submissionId: number;
}

export default function AnsweredQuestionCard({
  questao,
  numero,
  applicationId,
  submissionId,
}: Props) {
  const { saveCorrection } = useCorrectionStore();
  const toast = useToast();

  const [pontuacaoInput, setPontuacaoInput] = useState(
    String(questao.pontuacaoObtida ?? "")
  );
  const [feedbackInput, setFeedbackInput] = useState(
    questao.textoRevisao ?? ""
  );
  const [isSavingLocal, setIsSavingLocal] = useState(false);

  const isSelected = (altId: number) => {
    const dados = questao.dadosResposta;
    if (!dados) return false;

    if ("alternativa_id" in dados) return dados.alternativa_id === altId;
    if ("alternativas_id" in dados)
      return (dados.alternativas_id as number[]).includes(altId);
    return false;
  };

  const handleSave = async () => {
    const nota = parseFloat(pontuacaoInput.replace(",", "."));

    if (isNaN(nota) || nota < 0 || nota > questao.pontuacaoMaxima) {
      toast.add({
        title: "Valor inválido",
        description: `A nota deve ser entre 0 e ${questao.pontuacaoMaxima}`,
        color: "error",
      });
      return;
    }

    setIsSavingLocal(true);
    const success = await saveCorrection(
      applicationId,
      submissionId,
      questao.id,
      {
        pontuacao: nota,
        textoRevisao: feedbackInput,
        maxPoints: questao.pontuacaoMaxima,
      }
    );
    setIsSavingLocal(false);

    if (success) {
      toast.add({
        title: "Salvo!",
        description: "Correção atualizada com sucesso.",
        color: "success",
      });
    } else {
      toast.add({
        title: "Erro",
        description: "Não foi possível salvar.",
        color: "error",
      });
    }
  };

  let statusColor = "bg-gray-100";
  let statusText = "text-gray-600";
  let statusIcon = <Circle size={16} color="#6b7280" />;
  let statusLabel = "Não Corrigida";

  if (questao.estadoCorrecao === EstadoQuestaoCorrigida.CORRETA) {
    statusColor = "bg-green-100";
    statusText = "text-green-700";
    statusIcon = <CheckCircle2 size={16} color="#15803d" />;
    statusLabel = "Correta";
  } else if (questao.estadoCorrecao === EstadoQuestaoCorrigida.INCORRETA) {
    statusColor = "bg-red-100";
    statusText = "text-red-700";
    statusIcon = <XCircle size={16} color="#b91c1c" />;
    statusLabel = "Incorreta";
  } else if (
    questao.estadoCorrecao === EstadoQuestaoCorrigida.PARCIALMENTE_CORRETA
  ) {
    statusColor = "bg-yellow-100";
    statusText = "text-yellow-800";
    statusLabel = "Parcial";
  }

  return (
    <View className="bg-white p-4 rounded-xl border border-gray-200 shadow-sm mb-4">
      {/* Header da Questão */}
      <View className="flex-row justify-between items-start mb-4">
        <View className="flex-row items-center">
          <View className="w-8 h-8 bg-primary rounded-full items-center justify-center mr-3">
            <Text className="text-white font-bold">{numero}</Text>
          </View>
          <View
            className={`flex-row items-center px-2 py-1 rounded-md ${statusColor}`}
          >
            {statusIcon}
            <Text className={`ml-1 text-xs font-bold ${statusText}`}>
              {statusLabel}
            </Text>
          </View>
        </View>
        <Text className="text-xs text-gray-500 font-medium">
          {questao.pontuacaoObtida ?? 0}/{questao.pontuacaoMaxima} pts
        </Text>
      </View>

      {/* Enunciado (HTML via WebView) */}
      <View className="mb-4">
        <HtmlWithMath html={questao.titulo} />

        {questao.descricao ? (
          <View className="mt-2">
            <HtmlWithMath html={questao.descricao} textColor="#6b7280" />
          </View>
        ) : null}
      </View>

      {/* Área de Resposta */}
      <View className="border-t border-gray-100 pt-4">
        {questao.tipo === TipoQuestaoEnum.DISCURSIVA ? (
          // DISCURSIVA
          <View>
            <Text className="text-sm font-bold text-gray-700 mb-2 flex-row items-center">
              <MessageSquare size={14} color="#374151" /> Resposta do Aluno:
            </Text>
            <View className="bg-gray-50 p-3 rounded-lg border border-gray-200 mb-4">
              <HtmlWithMath
                html={
                  (questao.dadosResposta as any)?.texto ||
                  "<p style='color: #9ca3af; font-style: italic;'>Sem resposta.</p>"
                }
              />
            </View>

            {/* Formulário de Correção */}
            <View className="bg-blue-50 p-4 rounded-lg border border-blue-100">
              <Text className="text-sm font-bold text-blue-800 mb-3">
                Correção Manual
              </Text>

              <View className="flex-row gap-4 mb-3">
                <View className="flex-1">
                  <Text className="text-xs text-blue-600 mb-1">
                    Nota (Max: {questao.pontuacaoMaxima})
                  </Text>
                  <TextInput
                    className="bg-white border border-blue-200 rounded px-3 py-2 text-gray-900"
                    keyboardType="numeric"
                    value={pontuacaoInput}
                    onChangeText={setPontuacaoInput}
                  />
                </View>
              </View>

              <View className="mb-3">
                <Text className="text-xs text-blue-600 mb-1">
                  Feedback (Opcional)
                </Text>
                <TextInput
                  className="bg-white border border-blue-200 rounded px-3 py-2 text-gray-900 h-20"
                  multiline
                  textAlignVertical="top"
                  value={feedbackInput}
                  onChangeText={setFeedbackInput}
                  placeholder="Escreva um comentário para o aluno..."
                />
              </View>

              <TouchableOpacity
                onPress={handleSave}
                disabled={isSavingLocal}
                className="bg-blue-600 rounded-lg py-3 flex-row justify-center items-center"
              >
                {isSavingLocal ? (
                  <ActivityIndicator color="white" size="small" />
                ) : (
                  <>
                    <Save size={16} color="white" style={{ marginRight: 6 }} />
                    <Text className="text-white font-bold">
                      Salvar Correção
                    </Text>
                  </>
                )}
              </TouchableOpacity>
            </View>
          </View>
        ) : (
          // OBJETIVA / MULTIPLA ESCOLHA
          <View className="gap-2">
            {questao.alternativas.map((alt) => {
              const selected = isSelected(alt.id);
              const isCorrect = alt.isCorreto;

              let borderColor = "border-gray-200";
              let bgColor = "bg-white";
              let icon = <Circle size={20} color="#9ca3af" />;

              if (selected) {
                if (isCorrect) {
                  borderColor = "border-green-500";
                  bgColor = "bg-green-50";
                  icon = <CheckCircle2 size={20} color="#22c55e" />;
                } else {
                  borderColor = "border-red-500";
                  bgColor = "bg-red-50";
                  icon = <XCircle size={20} color="#ef4444" />;
                }
              } else if (isCorrect) {
                borderColor = "border-green-200";
                bgColor = "bg-green-50/50";
                icon = <CheckCircle2 size={20} color="#86efac" />;
              }

              return (
                <View
                  key={alt.id}
                  className={`flex-row p-3 rounded-lg border ${borderColor} ${bgColor} items-center`}
                >
                  <View className="mr-3">{icon}</View>
                  <View className="flex-1">
                    <HtmlWithMath
                      html={alt.descricao}
                      textColor={selected ? "#111827" : "#4b5563"}
                    />
                  </View>
                  {selected && (
                    <Text className="text-xs font-bold text-gray-500 ml-2">
                      Você
                    </Text>
                  )}
                </View>
              );
            })}
          </View>
        )}
      </View>
    </View>
  );
}

// provus-frontend-platform/app/components/Submissao/AnsweredQuestionCard/index.vue
<script setup lang="ts">
import TipoQuestaoEnum from "~/enums/TipoQuestaoEnum";
import EstadoQuestaoCorrigida from "~/enums/EstadoQuestaoCorrigida";
import type { AvaliadorQuestaoDetalheApiResponse } from "~/types/api/response/AvaliadorQuestaoDetalhe.response";
import { z } from "zod";

const props = defineProps<{
  questao: AvaliadorQuestaoDetalheApiResponse;
  numero: number;
}>();

const emit = defineEmits<{
  (
    e: "save-correction",
    payload: { pontuacao: number; textoRevisao: string }
  ): void;
}>();

const correctionSchema = z.object({
  pontuacao: z
    .number()
    .min(0, "Pontuação não pode ser negativa")
    .max(
      props.questao.pontuacaoMaxima,
      `Pontuação não pode ser maior que ${props.questao.pontuacaoMaxima}`
    ),
  textoRevisao: z.string().optional(),
});

const formCorrecao = reactive({
  pontuacao: props.questao.pontuacaoObtida ?? 0,
  textoRevisao: props.questao.textoRevisao ?? "",
});

const headerVisuals = computed(() => {
  const estado = props.questao.estadoCorrecao;
  const pontuacaoObtida = props.questao.pontuacaoObtida ?? 0;

  if (
    props.questao.tipo === TipoQuestaoEnum.DISCURSIVA &&
    (estado === EstadoQuestaoCorrigida.NAO_RESPONDIDA || estado === null) &&
    getStudentDiscursiveAnswer.value
  ) {
    return {
      text: `Aguardando Correção`,
      icon: "i-lucide-edit-3",
      colorClasses: "bg-blue-100 text-blue-600",
    };
  }

  switch (estado) {
    case EstadoQuestaoCorrigida.CORRETA:
      return {
        text: `Correta • ${pontuacaoObtida} ponto(s)`,
        icon: "i-lucide-check",
        colorClasses: "bg-green-100 text-green-600",
      };
    case EstadoQuestaoCorrigida.PARCIALMENTE_CORRETA:
      return {
        text: `Parcialmente Correta • ${pontuacaoObtida} ponto(s)`,
        icon: "i-lucide-check-circle",
        colorClasses: "bg-yellow-100 text-yellow-600",
      };
    case EstadoQuestaoCorrigida.INCORRETA:
      return {
        text: `Incorreta • ${pontuacaoObtida} ponto(s)`,
        icon: "i-lucide-x",
        colorClasses: "bg-red-100 text-red-600",
      };
    case EstadoQuestaoCorrigida.NAO_RESPONDIDA:
    default:
      return {
        text: `Não Respondida • 0 pontos`,
        icon: "i-lucide-minus-circle",
        colorClasses: "bg-gray-100 text-gray-600",
      };
  }
});

function isAlternativeSelected(alternativeId: number): boolean {
  const dados = props.questao.dadosResposta;
  if (!dados || typeof dados !== "object" || Object.keys(dados).length === 0)
    return false;
  if (
    "alternativa_id" in dados &&
    (typeof dados.alternativa_id === "number" || dados.alternativa_id === null)
  ) {
    return dados.alternativa_id === alternativeId;
  }
  if ("alternativas_id" in dados && Array.isArray(dados.alternativas_id)) {
    return dados.alternativas_id.includes(alternativeId);
  }
  return false;
}

const getStudentDiscursiveAnswer = computed(() => {
  const dados = props.questao.dadosResposta;
  if (
    dados &&
    typeof dados === "object" &&
    "texto" in dados &&
    typeof dados.texto === "string"
  ) {
    return dados.texto;
  }
  return null;
});
</script>

<template>
  <UCard v-if="questao" :id="`question-${questao.id}`">
    <div class="flex items-start justify-between mb-4 flex-wrap gap-2">
      <div class="flex items-center space-x-3">
        <div
          :class="headerVisuals.colorClasses"
          class="w-8 h-8 rounded-full flex items-center justify-center"
        >
          <Icon :name="headerVisuals.icon" class="text-sm" />
        </div>
        <span class="text-sm font-medium" :class="headerVisuals.colorClasses">
          {{ headerVisuals.text }}
        </span>
      </div>
      <span class="text-sm text-gray-500"
        >Questão {{ numero }} • {{ questao.pontuacaoMaxima }} Ponto(s)</span
      >
    </div>

    <h3 class="text-lg font-semibold text-gray-900 mb-3">
      {{ questao.titulo }}
    </h3>
    <p v-if="questao.descricao" class="text-sm text-gray-500 mb-4">
      {{ questao.descricao }}
    </p>

    <div class="space-y-3">
      <template v-if="questao.tipo === TipoQuestaoEnum.DISCURSIVA">
        <div class="p-4 bg-gray-50 border border-gray-200 rounded-lg">
          <div class="flex items-center space-x-2 mb-2">
            <Icon name="i-lucide-message-square" class="text-gray-500" />
            <span class="text-sm font-medium text-gray-600"
              >Resposta do Aluno</span
            >
          </div>
          <p
            v-if="getStudentDiscursiveAnswer"
            class="text-gray-900 whitespace-pre-wrap"
          >
            {{ getStudentDiscursiveAnswer }}
          </p>
          <p v-else class="text-gray-500 italic">Aluno não respondeu.</p>
        </div>
        <div
          v-if="questao.exemploRespostaIa"
          class="p-4 bg-blue-50 border border-blue-200 rounded-lg"
        >
          <div class="flex items-center space-x-2 mb-2">
            <Icon name="i-lucide-lightbulb" class="text-blue-600" />
            <span class="text-sm font-medium text-blue-600"
              >Resposta Esperada / Gabarito</span
            >
          </div>
          <p class="text-gray-700 whitespace-pre-wrap">
            {{ questao.exemploRespostaIa }}
          </p>
        </div>
      </template>

      <template
        v-else-if="questao.alternativas && questao.alternativas.length > 0"
      >
        <div
          v-for="alt in questao.alternativas"
          :key="alt.id"
          class="flex items-center space-x-3 p-3 border rounded-lg"
          :class="{
            'bg-green-50 border-green-200': alt.isCorreto,
            'bg-red-50 border-red-200':
              !alt.isCorreto && isAlternativeSelected(alt.id),
            'bg-gray-50 border-gray-200':
              !alt.isCorreto && !isAlternativeSelected(alt.id),
          }"
        >
          <Icon
            v-if="alt.isCorreto"
            name="i-lucide-check-circle-2"
            class="text-green-600 shrink-0"
          />
          <Icon
            v-else-if="!alt.isCorreto && isAlternativeSelected(alt.id)"
            name="i-lucide-x-circle"
            class="text-red-600 shrink-0"
          />
          <Icon v-else name="i-lucide-circle" class="text-gray-400 shrink-0" />
          <span class="text-gray-900 flex-1">{{ alt.descricao }}</span>
          <UBadge
            v-if="isAlternativeSelected(alt.id)"
            color="info"
            variant="subtle"
            size="xs"
            class="ml-auto shrink-0"
            >Sua Resposta</UBadge
          >
          <UBadge
            v-if="alt.isCorreto"
            color="secondary"
            variant="subtle"
            size="xs"
            class="ml-2 shrink-0"
            >Gabarito</UBadge
          >
        </div>
        <div
          v-if="questao.exemploRespostaIa"
          class="mt-4 p-4 bg-blue-50 border border-blue-200 rounded-lg"
        >
          <h4
            class="font-semibold text-sm text-blue-800 mb-1 flex items-center gap-1.5"
          >
            <Icon name="i-lucide-info" class="h-4 w-4" /> Explicação do
            Gabarito:
          </h4>
          <p class="text-sm text-blue-700 whitespace-pre-wrap">
            {{ questao.exemploRespostaIa }}
          </p>
        </div>
      </template>
    </div>

    <template v-if="questao.tipo === TipoQuestaoEnum.DISCURSIVA">
      <UForm
        :schema="correctionSchema"
        :state="formCorrecao"
        class="mt-6 pt-6 border-t border-gray-200 space-y-4"
        @submit="emit('save-correction', formCorrecao)"
      >
        <h4 class="text-md font-semibold text-primary">
          Formulário de Correção Manual
        </h4>
        <UFormField
          label="Pontuação Atribuída"
          name="pontuacao"
          required
          :hint="`Valor máximo: ${questao.pontuacaoMaxima} pontos`"
        >
          <UInputNumber
            v-model="formCorrecao.pontuacao"
            :min="0"
            :max="questao.pontuacaoMaxima"
            :step="0.5"
          />
        </UFormField>
        <UFormField
          label="Feedback para o Aluno (Opcional)"
          name="textoRevisao"
        >
          <UTextarea
            v-model="formCorrecao.textoRevisao"
            placeholder="Digite seu feedback aqui..."
            class="flex"
            :rows="3"
          />
        </UFormField>
        <UButton
          type="submit"
          label="Salvar Correção"
          color="secondary"
          icon="i-lucide-check"
        />
      </UForm>
    </template>
  </UCard>
</template>
