// provus-frontend-platform/app/pages/Avaliador/Perfil/index.vue
<script setup lang="ts">
import { useUserStore } from "~/store/userStore";
import Breadcrumbs from "@/components/Breadcrumbs/index.vue"; 

definePageMeta({
  layout: "default",
});

const userStore = useUserStore();
const toast = useToast();
const breadcrumbs = [
  { label: "Home", to: "/home" },
  { label: "Perfil", disabled: true },
];
const form = reactive({
  nome: "",
  email: "",
});

const passwords = reactive({
  current: "",
  new: "",
  confirm: "",
});

const showCurrentPassword = ref(false);
const showNewPassword = ref(false);
const showConfirmPassword = ref(false);

onMounted(async () => {
  if (!userStore.user) {
    await userStore.fetchCurrentUser();
  }
  if (userStore.user) {
    form.nome = userStore.user.nome;
    form.email = userStore.user.email;
  }
});

const canSave = computed(() => {
  return (
    form.nome.length >= 3 &&
    passwords.current.length >= 6 &&
    (!passwords.new || passwords.new === passwords.confirm)
  );
});

async function handleSaveChanges() {
  if (!canSave.value) {
    toast.add({
      title: "Dados incompletos",
      description:
        "Verifique o nome e certifique-se de digitar sua senha atual para confirmar as alterações.",
      color: "warning",
    });
    return;
  }

  if (passwords.new && passwords.new.length < 6) {
    toast.add({
      title: "Nova senha inválida",
      description: "A nova senha deve ter no mínimo 6 caracteres.",
      color: "warning",
    });
    return;
  }

  const success = await userStore.updateProfile({
    nome: form.nome,
    senha: passwords.current,
    novaSenha: passwords.new,
  });

  if (success) {
    toast.add({
      title: "Perfil Atualizado!",
      description: "Suas informações foram salvas com sucesso.",
      icon: "i-lucide-check-circle",
      color: "secondary",
    });
    passwords.current = "";
    passwords.new = "";
    passwords.confirm = "";
  }
}

async function handleSendResetEmail() {
  if (!form.email) return;

  const success = await userStore.requestPasswordReset(form.email);
  if (success) {
    toast.add({
      title: "E-mail enviado",
      description: "Verifique sua caixa de entrada para redefinir a senha.",
      icon: "i-lucide-mail",
      color: "info",
    });
  } else {
    toast.add({
      title: "Erro",
      description: "Não foi possível processar a solicitação.",
      color: "error",
    });
  }
}
</script>

<template>
  <div class="mx-auto px-4 sm:px-6 lg:px-8 py-8">
    <Breadcrumbs :items="breadcrumbs" />
    <div class="flex items-center mb-8">
      <div>
        <h1 class="text-3xl font-bold text-primary">Configurações do Perfil</h1>
        <p class="text-gray-600 mt-1">
          Gerencie suas informações de conta e preferências
        </p>
      </div>
    </div>

    <div class="mx-auto">
      <UCard>
        <form class="space-y-8" @submit.prevent="handleSaveChanges">
          <div class="space-y-6">
            <h3 class="text-lg font-semibold text-gray-900 flex items-center">
              <Icon name="i-lucide-user" class="mr-2 text-primary" />
              Informações Pessoais
            </h3>

            <div class="grid grid-cols-1 gap-4">
              <UFormField label="Nome Completo" class="w-full" required>
                <UInput
                  v-model="form.nome"
                  size="lg"
                  class="w-full"
                  placeholder="Seu nome"
                />
              </UFormField>

              <UFormField
                label="E-mail (Login)"
                help="O e-mail não pode ser alterado diretamente."
              >
                <UInput
                  v-model="form.email"
                  type="email"
                  size="lg"
                  icon="i-lucide-mail"
                  class="w-full"
                  disabled
                />
              </UFormField>
            </div>
          </div>

          <div class="space-y-6">
            <div class="flex items-center justify-between">
              <h3 class="text-lg font-semibold text-gray-900 flex items-center">
                <Icon name="i-lucide-shield-check" class="mr-2 text-primary" />
                Segurança e Senha
              </h3>
              <UButton
                variant="link"
                color="primary"
                label="Esqueci minha senha atual"
                @click="handleSendResetEmail"
              />
            </div>

            <div class="space-y-4">
              <UAlert
                icon="i-lucide-info"
                color="primary"
                variant="subtle"
                title="Confirmação Necessária"
                description="Para alterar seu nome ou definir uma nova senha, você deve digitar sua senha atual abaixo."
              />

              <UFormField
                label="Senha Atual (Obrigatório para salvar)"
                required
              >
                <UInput
                  v-model="passwords.current"
                  :type="showCurrentPassword ? 'text' : 'password'"
                  placeholder="Digite sua senha atual para confirmar alterações"
                  size="lg"
                  class="w-full"
                >
                  <template #trailing>
                    <UButton
                      color="primary"
                      variant="link"
                      :icon="
                        showCurrentPassword
                          ? 'i-lucide-eye-off'
                          : 'i-lucide-eye'
                      "
                      @click="showCurrentPassword = !showCurrentPassword"
                    />
                  </template>
                </UInput>
              </UFormField>

              <div
                class="grid grid-cols-1 md:grid-cols-2 gap-4 pt-4 border-t border-gray-100"
              >
                <UFormField label="Nova Senha (Opcional)">
                  <UInput
                    v-model="passwords.new"
                    :type="showNewPassword ? 'text' : 'password'"
                    placeholder="Deixe em branco para manter a atual"
                    size="lg"
                    class="w-full"
                  >
                    <template #trailing>
                      <UButton
                        color="primary"
                        variant="link"
                        :icon="
                          showNewPassword ? 'i-lucide-eye-off' : 'i-lucide-eye'
                        "
                        @click="showNewPassword = !showNewPassword"
                      />
                    </template>
                  </UInput>
                </UFormField>

                <UFormField label="Confirme a Nova Senha">
                  <UInput
                    v-model="passwords.confirm"
                    :type="showConfirmPassword ? 'text' : 'password'"
                    placeholder="Repita a nova senha"
                    size="lg"
                    class="w-full"
                    :color="
                      passwords.new && passwords.new !== passwords.confirm
                        ? 'error'
                        : 'primary'
                    "
                  >
                    <template #trailing>
                      <UButton
                        color="primary"
                        variant="link"
                        :icon="
                          showConfirmPassword
                            ? 'i-lucide-eye-off'
                            : 'i-lucide-eye'
                        "
                        @click="showConfirmPassword = !showConfirmPassword"
                      />
                    </template>
                  </UInput>
                </UFormField>
              </div>
            </div>
          </div>

          <div
            class="flex flex-col sm:flex-row gap-4 pt-6 border-t border-gray-200"
          >
            <UButton
              type="button"
              block
              size="lg"
              color="error"
              variant="subtle"
              class="w-full"
              icon="i-lucide-x"
              to="/home"
            >
              Cancelar
            </UButton>

            <UButton
              type="submit"
              block
              size="lg"
              color="secondary"
              icon="i-lucide-save"
              :loading="userStore.isLoading"
              :disabled="!canSave"
            >
              Salvar Alterações
            </UButton>
          </div>
        </form>
      </UCard>
    </div>
  </div>
</template>

// provus-mobile-platform/app/perfil.tsx
import React, { useEffect, useState } from "react";
import {
  View,
  Text,
  TextInput,
  TouchableOpacity,
  ScrollView,
  Alert,
  ActivityIndicator,
  KeyboardAvoidingView,
  Platform,
} from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useRouter, Stack } from "expo-router";
import {
  ArrowLeft,
  User,
  Mail,
  Lock,
  Eye,
  EyeOff,
  Save,
  LogOut,
  ShieldCheck,
} from "lucide-react-native";
import { useUserStore } from "../stores/userStore";
import { useToast } from "../hooks/useToast";

export default function ProfileScreen() {
  const router = useRouter();
  const { user, updateProfile, requestPasswordReset, logout, isLoading } =
    useUserStore();
  const toast = useToast();

  const [name, setName] = useState("");
  const [email, setEmail] = useState("");

  const [currentPassword, setCurrentPassword] = useState("");
  const [newPassword, setNewPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");

  const [showCurrent, setShowCurrent] = useState(false);
  const [showNew, setShowNew] = useState(false);
  const [showConfirm, setShowConfirm] = useState(false);

  useEffect(() => {
    if (user) {
      setName(user.nome);
      setEmail(user.email);
    }
  }, [user]);

  const handleSave = async () => {
    if (name.length < 3) {
      toast.add({
        title: "Nome curto",
        description: "O nome deve ter pelo menos 3 caracteres.",
        color: "warning",
      });
      return;
    }
    if (currentPassword.length < 6) {
      toast.add({
        title: "Senha obrigatória",
        description: "Digite sua senha atual para salvar as alterações.",
        color: "warning",
      });
      return;
    }
    if (newPassword && newPassword !== confirmPassword) {
      toast.add({
        title: "Senhas não conferem",
        description: "A nova senha e a confirmação devem ser iguais.",
        color: "error",
      });
      return;
    }
    if (newPassword && newPassword.length < 6) {
      toast.add({
        title: "Senha fraca",
        description: "A nova senha deve ter no mínimo 6 caracteres.",
        color: "warning",
      });
      return;
    }

    const success = await updateProfile({
      nome: name,
      senha: currentPassword,
      novaSenha: newPassword || "",
    });

    if (success) {
      toast.add({
        title: "Sucesso!",
        description: "Perfil atualizado.",
        color: "success",
      });
      setCurrentPassword("");
      setNewPassword("");
      setConfirmPassword("");
    }
  };

  const handleForgotPassword = async () => {
    if (!email) return;
    Alert.alert(
      "Redefinir Senha",
      `Enviar link de redefinição para ${email}?`,
      [
        { text: "Cancelar", style: "cancel" },
        {
          text: "Enviar",
          onPress: async () => {
            const success = await requestPasswordReset(email);
            if (success) {
              toast.add({
                title: "E-mail enviado",
                description: "Verifique sua caixa de entrada.",
                color: "info",
              });
            }
          },
        },
      ]
    );
  };

  const handleLogout = async () => {
    Alert.alert("Sair", "Tem certeza que deseja sair?", [
      { text: "Cancelar", style: "cancel" },
      {
        text: "Sair",
        style: "destructive",
        onPress: async () => {
          await logout();
          router.replace("/login");
        },
      },
    ]);
  };

  const renderPasswordInput = (
    label: string,
    value: string,
    onChange: (text: string) => void,
    show: boolean,
    toggleShow: () => void,
    placeholder: string
  ) => (
    <View className="mb-4">
      <Text className="text-sm font-medium text-gray-700 mb-1.5">{label}</Text>
      <View className="flex-row items-center border border-gray-300 rounded-lg px-3 py-3 bg-white focus:border-primary">
        <Lock size={20} color="#9ca3af" />
        <TextInput
          className="flex-1 ml-3 text-gray-900"
          placeholder={placeholder}
          placeholderTextColor="#9ca3af"
          secureTextEntry={!show}
          value={value}
          onChangeText={onChange}
        />
        <TouchableOpacity onPress={toggleShow} className="p-1">
          {show ? (
            <EyeOff size={20} color="#6b7280" />
          ) : (
            <Eye size={20} color="#6b7280" />
          )}
        </TouchableOpacity>
      </View>
    </View>
  );

  return (
    <SafeAreaView className="flex-1 bg-gray-50" edges={["top"]}>
      <Stack.Screen options={{ headerShown: false }} />

      {/* Header */}
      <View className="px-4 py-3 flex-row items-center bg-white border-b border-gray-200">
        <TouchableOpacity onPress={() => router.back()} className="p-2 mr-2">
          <ArrowLeft size={24} color="#374151" />
        </TouchableOpacity>
        <Text className="text-lg font-bold text-gray-900">
          Configurações do Perfil
        </Text>
      </View>

      <KeyboardAvoidingView
        behavior={Platform.OS === "ios" ? "padding" : "height"}
        className="flex-1"
      >
        <ScrollView contentContainerStyle={{ padding: 24 }}>
          {/* Seção: Info Pessoal */}
          <View className="mb-8">
            <View className="flex-row items-center mb-4">
              <User size={20} color="#004e8c" />
              <Text className="text-lg font-bold text-gray-900 ml-2">
                Informações Pessoais
              </Text>
            </View>

            <View className="bg-white p-5 rounded-xl border border-gray-200 shadow-sm space-y-4">
              <View>
                <Text className="text-sm font-medium text-gray-700 mb-1.5">
                  Nome Completo
                </Text>
                <View className="flex-row items-center border border-gray-300 rounded-lg px-3 py-3 bg-white">
                  <User size={20} color="#9ca3af" />
                  <TextInput
                    className="flex-1 ml-3 text-gray-900"
                    value={name}
                    onChangeText={setName}
                    placeholder="Seu nome"
                  />
                </View>
              </View>

              <View>
                <Text className="text-sm font-medium text-gray-700 mb-1.5">
                  E-mail (Login)
                </Text>
                <View className="flex-row items-center border border-gray-300 rounded-lg px-3 py-3 bg-gray-100">
                  <Mail size={20} color="#9ca3af" />
                  <TextInput
                    className="flex-1 ml-3 text-gray-500"
                    value={email}
                    editable={false}
                  />
                </View>
                <Text className="text-xs text-gray-400 mt-1">
                  O e-mail não pode ser alterado.
                </Text>
              </View>
            </View>
          </View>

          {/* Seção: Segurança */}
          <View className="mb-8">
            <View className="flex-row items-center justify-between mb-4">
              <View className="flex-row items-center">
                <ShieldCheck size={20} color="#004e8c" />
                <Text className="text-lg font-bold text-gray-900 ml-2">
                  Segurança
                </Text>
              </View>
              <TouchableOpacity onPress={handleForgotPassword}>
                <Text className="text-sm text-primary font-medium">
                  Esqueci minha senha
                </Text>
              </TouchableOpacity>
            </View>

            <View className="bg-white p-5 rounded-xl border border-gray-200 shadow-sm">
              <View className="bg-blue-50 p-3 rounded-lg mb-4 flex-row items-center border border-blue-100">
                <View className="mr-3">
                  <ShieldCheck size={18} color="#3b82f6" />
                </View>
                <Text className="text-xs text-blue-700 flex-1">
                  Para confirmar qualquer alteração (nome ou senha), digite sua
                  senha atual.
                </Text>
              </View>

              {renderPasswordInput(
                "Senha Atual (Obrigatório)",
                currentPassword,
                setCurrentPassword,
                showCurrent,
                () => setShowCurrent(!showCurrent),
                "Sua senha atual"
              )}

              <View className="h-[1px] bg-gray-100 my-2" />

              {renderPasswordInput(
                "Nova Senha (Opcional)",
                newPassword,
                setNewPassword,
                showNew,
                () => setShowNew(!showNew),
                "Deixe em branco para manter"
              )}

              {renderPasswordInput(
                "Confirmar Nova Senha",
                confirmPassword,
                setConfirmPassword,
                showConfirm,
                () => setShowConfirm(!showConfirm),
                "Repita a nova senha"
              )}
            </View>
          </View>

          {/* Botões de Ação */}
          <View className="gap-4 mb-10">
            <TouchableOpacity
              onPress={handleSave}
              disabled={isLoading}
              className={`flex-row items-center justify-center bg-primary rounded-xl py-4 shadow-sm ${
                isLoading ? "opacity-70" : ""
              }`}
            >
              {isLoading ? (
                <ActivityIndicator color="white" />
              ) : (
                <>
                  <Save size={20} color="white" style={{ marginRight: 8 }} />
                  <Text className="text-white font-bold text-lg">
                    Salvar Alterações
                  </Text>
                </>
              )}
            </TouchableOpacity>

            <TouchableOpacity
              onPress={handleLogout}
              className="flex-row items-center justify-center bg-red-50 border border-red-100 rounded-xl py-4"
            >
              <LogOut size={20} color="#ef4444" style={{ marginRight: 8 }} />
              <Text className="text-red-600 font-bold text-lg">
                Sair da Conta
              </Text>
            </TouchableOpacity>
          </View>
        </ScrollView>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
}
