// provus-mobile-platform/components/ApplicationCard.tsx
import React from "react";
import { View, Text, TouchableOpacity } from "react-native";
import {
  CalendarClock,
  CheckCircle2,
  XCircle,
  PauseCircle,
  FilePlus2,
  Hourglass,
} from "lucide-react-native";
import { router } from "expo-router";
import { AplicacaoEntity } from "../types/entities/Aplicacao.entity";
import { EstadoAplicacaoEnum } from "../enums/EstadoAplicacaoEnum";
import { stripHtml } from "../utils/stripHtml";

interface Props {
  item: AplicacaoEntity;
}

export default function ApplicationCard({ item }: Props) {
  const getStatusVisuals = (estado: EstadoAplicacaoEnum) => {
    switch (estado) {
      case EstadoAplicacaoEnum.PAUSADA:
        return {
          icon: PauseCircle,
          bg: "bg-yellow-100",
          text: "text-yellow-800",
          iconColor: "#ca8a04",
        };
      case EstadoAplicacaoEnum.EM_ANDAMENTO:
        return {
          icon: Hourglass,
          bg: "bg-yellow-100",
          text: "text-yellow-800",
          iconColor: "#ca8a04",
        };
      case EstadoAplicacaoEnum.AGENDADA:
        return {
          icon: CalendarClock,
          bg: "bg-blue-100",
          text: "text-blue-800",
          iconColor: "#2563eb",
        };
      case EstadoAplicacaoEnum.CONCLUIDA:
      case EstadoAplicacaoEnum.FINALIZADA:
        return {
          icon: CheckCircle2,
          bg: "bg-green-100",
          text: "text-green-800",
          iconColor: "#16a34a",
        };
      case EstadoAplicacaoEnum.CANCELADA:
        return {
          icon: XCircle,
          bg: "bg-red-100",
          text: "text-red-800",
          iconColor: "#dc2626",
        };
      default:
        return {
          icon: FilePlus2,
          bg: "bg-gray-100",
          text: "text-gray-800",
          iconColor: "#4b5563",
        };
    }
  };

  const visuals = getStatusVisuals(item.estado);
  const IconComponent = visuals.icon;

  const formattedDate =
    item.estado === EstadoAplicacaoEnum.AGENDADA
      ? item.dataInicio.toLocaleDateString("pt-BR")
      : item.dataFim.toLocaleDateString("pt-BR");

  const isFinished =
    item.estado === EstadoAplicacaoEnum.FINALIZADA ||
    item.estado === EstadoAplicacaoEnum.CONCLUIDA ||
    item.estado === EstadoAplicacaoEnum.CANCELADA;

  const handlePress = () => {
    if (isFinished) {
      router.push(`/aplicacao/${item.id}` as any);
    } else {
      router.push(`/monitoramento/${item.id}` as any);
    }
  };
  return (
    <TouchableOpacity
      onPress={handlePress}
      className="bg-white p-4 rounded-xl border border-gray-200 mb-4 shadow-sm"
    >
      <View className="flex-row items-start">
        {/* Ícone do Status */}
        <View
          className={`w-12 h-12 rounded-lg items-center justify-center mr-3 ${visuals.bg}`}
        >
          <IconComponent color={visuals.iconColor} size={24} />
        </View>

        {/* Conteúdo */}
        <View className="flex-1">
          <Text
            className="text-base font-bold text-gray-900 mb-1"
            numberOfLines={2}
          >
            {stripHtml(item.avaliacao.titulo)}
          </Text>

          <Text className="text-xs text-gray-500 mb-2">
            {item.estado === EstadoAplicacaoEnum.AGENDADA
              ? "Agendada para: "
              : "Data: "}
            {formattedDate}
          </Text>

          <View className="flex-row items-center flex-wrap gap-2">
            {/* Badge de Status */}
            <View className={`px-2 py-1 rounded-md ${visuals.bg}`}>
              <Text className={`text-xs font-medium ${visuals.text}`}>
                {item.estado}
              </Text>
            </View>

            {/* Badge de Participantes */}
            <Text className="text-xs text-gray-500">
              {item.totalSubmissoes} participante(s)
            </Text>
          </View>
        </View>
      </View>
    </TouchableOpacity>
  );
}

// provus-frontend-platform/app/components/Aplicacoes/ApplicationCard/index.vue
<script setup lang="ts">
import EstadoAplicacaoEnum from "~/enums/EstadoAplicacaoEnum";
import type { AplicacaoEntity } from "~/types/entities/Aplicacao.entity";

const props = defineProps<{
  item: AplicacaoEntity;
}>();

const emit = defineEmits([
  "view-config",
  "apply-now",
  "cancel-schedule",
  "reopen",
  "start-now",
]);

const isCriada = computed(
  () => props.item.estado === EstadoAplicacaoEnum.CRIADA
);
const isEmAndamento = computed(
  () => props.item.estado === EstadoAplicacaoEnum.EM_ANDAMENTO
);
const isAgendada = computed(
  () => props.item.estado === EstadoAplicacaoEnum.AGENDADA
);
const isPausada = computed(
  () => props.item.estado === EstadoAplicacaoEnum.PAUSADA
);

const participantesInfo = computed(() => {
  return props.item.totalSubmissoes > 0
    ? props.item.totalSubmissoes === 1
      ? "1 participante"
      : `${props.item.totalSubmissoes} participantes`
    : "-- participantes";
});

const mediaInfo = computed(() => {
  return props.item.mediaGeralPercentual !== null
    ? `${props.item.mediaGeralPercentual?.toFixed(0)}%`
    : "-- %";
});

const isFinishedOrCancelled = computed(() =>
  [
    EstadoAplicacaoEnum.CONCLUIDA,
    EstadoAplicacaoEnum.FINALIZADA,
    EstadoAplicacaoEnum.CANCELADA,
  ].includes(props.item.estado)
);

const statusVisuals = computed(() => {
  switch (props.item.estado) {
    case EstadoAplicacaoEnum.PAUSADA:
      return {
        icon: "i-lucide-pause-circle",
        iconBgColor: "bg-yellow-100",
        iconTextColor: "text-yellow-600",
        statusBgColor: "bg-yellow-100",
        statusTextColor: "text-yellow-800",
      };
    case EstadoAplicacaoEnum.EM_ANDAMENTO:
      return {
        icon: "i-lucide-hourglass",
        iconBgColor: "bg-yellow-100",
        iconTextColor: "text-yellow-600",
        statusBgColor: "bg-yellow-100",
        statusTextColor: "text-yellow-800",
      };
    case EstadoAplicacaoEnum.AGENDADA:
      return {
        icon: "i-lucide-calendar-clock",
        iconBgColor: "bg-blue-200",
        iconTextColor: "text-blue-600",
        statusBgColor: "bg-blue-200",
        statusTextColor: "text-blue-800",
      };
    case EstadoAplicacaoEnum.CONCLUIDA:
    case EstadoAplicacaoEnum.FINALIZADA:
      return {
        icon: "i-lucide-check-circle-2",
        iconBgColor: "bg-green-100",
        iconTextColor: "text-green-600",
        statusBgColor: "bg-green-100",
        statusTextColor: "text-green-800",
      };
    case EstadoAplicacaoEnum.CANCELADA:
      return {
        icon: "i-lucide-x-circle",
        iconBgColor: "bg-red-100",
        iconTextColor: "text-red-600",
        statusBgColor: "bg-red-100",
        statusTextColor: "text-red-800",
      };
    default:
      return {
        icon: "i-lucide-file-plus-2",
        iconBgColor: "bg-green-100",
        iconTextColor: "text-green-600",
        statusBgColor: "bg-green-100",
        statusTextColor: "text-green-800",
      };
  }
});

const formattedDate = computed(() => {
  const dateToFormat =
    props.item.estado === EstadoAplicacaoEnum.AGENDADA
      ? props.item.dataInicio
      : props.item.dataFim;
  return new Date(dateToFormat).toLocaleDateString("pt-BR", {
    day: "2-digit",
    month: "long",
    year: "numeric",
  });
});
</script>

<template>
  <UCard>
    <template #header>
      <div class="flex items-center justify-between">
        <div class="flex items-center space-x-3">
          <div
            :class="statusVisuals.iconBgColor"
            class="w-12 h-12 rounded-lg flex items-center justify-center"
          >
            <Icon
              :name="statusVisuals.icon"
              :class="statusVisuals.iconTextColor"
              class="text-xl"
            />
          </div>
          <div>
            <h3 class="font-semibold text-gray-900">
              {{ props.item.avaliacao.titulo }}
            </h3>
          </div>
        </div>
      </div>
    </template>

    <div class="space-y-3 mb-4">
      <div class="flex items-center justify-between text-sm">
        <span class="text-gray-600">{{
          item.estado === "Agendada" ? "Agendado para:" : "Data:"
        }}</span>
        <span class="font-medium text-gray-900">{{ formattedDate }}</span>
      </div>
      <div class="flex items-center justify-between text-sm">
        <UTooltip text="Disponível após a finalização da aplicação">
          <span class="text-gray-600">Alunos:</span>
        </UTooltip>
        <span class="font-medium text-gray-900">{{ participantesInfo }}</span>
      </div>
      <div class="flex items-center justify-between text-sm">
        <UTooltip text="Disponível após a finalização da aplicação">
          <span class="text-gray-600">Média:</span>
        </UTooltip>
        <span class="font-medium text-secondary">{{ mediaInfo }}</span>
      </div>
      <div class="flex items-center justify-between text-sm">
        <span class="text-gray-600">Status:</span>
        <UBadge
          :class="[statusVisuals.statusBgColor, statusVisuals.statusTextColor]"
          variant="subtle"
        >
          {{ props.item.estado }}
        </UBadge>
      </div>
    </div>

    <template v-if="isEmAndamento || isPausada">
      <UButton
        block
        color="primary"
        variant="solid"
        icon="i-lucide-activity"
        :to="`/aplicacoes/aplicacao/${item.id}/monitoramento`"
      >
        Monitorar
      </UButton>
      <UButton
        block
        color="primary"
        variant="outline"
        icon="i-lucide-settings-2"
        class="mt-2"
        @click="emit('view-config', item)"
      >
        Ver Configuração Completa
      </UButton>
    </template>

    <template v-else-if="isFinishedOrCancelled">
      <div class="flex items-center space-x-2">
        <UButton block :to="`/aplicacoes/aplicacao/${item.id}`">
          Ver Detalhes
        </UButton>
        <UButton
          block
          color="secondary"
          variant="solid"
          :to="`/aplicacoes/aplicacao/${item.id}/resultados`"
        >
          Resultados
        </UButton>
      </div>
      <UButton
        v-if="item.estado !== 'Cancelada'"
        block
        color="primary"
        variant="soft"
        icon="i-lucide-refresh-cw"
        class="mt-2"
        @click="emit('reopen', item)"
      >
        Reabrir Aplicação
      </UButton>
      <UButton
        block
        color="primary"
        variant="outline"
        icon="i-lucide-settings-2"
        class="mt-2"
        @click="emit('view-config', item)"
      >
        Ver Configuração Completa
      </UButton>
    </template>

    <template v-else-if="isCriada">
      <UButton
        block
        color="secondary"
        variant="solid"
        icon="i-lucide-play"
        @click="emit('start-now', item)"
      >
        Iniciar Agora
      </UButton>
    </template>

    <template v-else-if="isAgendada">
      <div class="flex items-center space-x-2 mb-2">
        <UButton
          block
          color="secondary"
          icon="i-lucide-play-circle"
          @click="emit('apply-now', item)"
        >
          Aplicar Agora
        </UButton>
        <UButton
          block
          variant="outline"
          icon="i-lucide-pencil"
          :to="`/avaliacao/editor/${item.avaliacao.id}`"
        >
          Editar
        </UButton>
      </div>
      <UButton
        block
        color="error"
        variant="subtle"
        icon="i-lucide-calendar-x-2"
        @click="emit('cancel-schedule', item)"
      >
        Cancelar Agendamento
      </UButton>
      <UButton
        block
        color="primary"
        variant="outline"
        icon="i-lucide-settings-2"
        class="mt-2"
        @click="emit('view-config', item)"
      >
        Ver Configuração Completa
      </UButton>
    </template>
  </UCard>
</template>
